# Generated by Django 4.2.7 on 2024-03-05 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_message_options_remove_cart_store_chat_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='messagereport',
            name='reporting_user',
        ),
        migrations.AddField(
            model_name='messagereport',
            name='reporting_user',
            field=models.ManyToManyField(related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
