# Generated by Django 4.2.7 on 2024-02-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_cart_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['updated', '-created']},
        ),
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.ImageField(default='storebanner.webp', null=True, upload_to=''),
        ),
    ]
