# Generated by Django 4.2.7 on 2024-08-15 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_post_original_post_remove_post_shares_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShareComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.share')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
