# Generated by Django 4.2.7 on 2024-03-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_messagereport_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagereport',
            old_name='reporting_user',
            new_name='reporting_users',
        ),
    ]
