# Generated by Django 4.2.7 on 2024-08-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_chat_video_alter_chat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file.', null=True, upload_to='post_videos/'),
        ),
    ]
