# Generated by Django 4.2.7 on 2024-09-13 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='room',
            name='question',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenters', to=settings.AUTH_USER_MODEL),
        ),
    ]
