# Generated by Django 4.2.7 on 2024-04-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_eventmess_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmess',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='base.event'),
        ),
    ]
