# Generated by Django 4.2.7 on 2024-09-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_joinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharecomment',
            name='share',
        ),
        migrations.RemoveField(
            model_name='sharecomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventMessage',
        ),
        migrations.DeleteModel(
            name='ShareComment',
        ),
    ]
