# Generated by Django 4.2.7 on 2024-04-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_eventmessage_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='waiting', max_length=200, null=True),
        ),
    ]
