# Generated by Django 4.2.7 on 2024-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='waiting', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(default='waiting', max_length=200, null=True),
        ),
    ]
