# Generated by Django 4.2.7 on 2024-06-11 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_message_options_store_address_store_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
