# Generated by Django 4.2.7 on 2024-06-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_event_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('US', 'User'), ('MO', 'Moder')], default='US', max_length=2, null=True),
        ),
    ]
